#!/bin/bash

# -------------------------------
# This simple script downloads and installs a Minecraft server onto your computer/server.
# Made by NorthernChicken: https://github.com/NorthernChicken
# Repo: https://github.com/NorthernChicken/MineInstall
# -------------------------------

server_version="1.20.6"
server_link="https://piston-data.mojang.com/v1/objects/145ff0858209bcfc164859ba735d4199aafa1eea/server.jar"
server_run="java -Xmx1024M -Xms1024M -jar server.jar nogui"

server_directory=~/server

green='\e[42m'
red='\e[31m'
bold='\e[1m'
clear='\e[0m'

install_java() {
    distribution=$(awk -F= '/^NAME/{print $2}' /etc/os-release)
    if [[ "$distribution" == *"Ubuntu"* ]] || [[ "$distribution" == *"Debian"* ]]; then
        sudo apt update
        sudo apt install -y default-jre
    elif [[ "$distribution" == *"CentOS"* ]] || [[ "$distribution" == *"Fedora"* ]]; then
        sudo yum install -y java
    elif [[ "$distribution" == *"Arch"* ]]; then
        sudo pacman -Sy --noconfirm jre-openjdk
    else
        echo -e "${red}${bold}Error: Unsupported distribution. Please install Java manually.${clear}"
        exit 1
    fi
}

# Check if Java is installed
check_java() {
    if ! command -v java &>/dev/null; then
        echo -e "${red}${bold}Java is not installed. Installing Java...${clear}"
        install_java
        if ! command -v java &>/dev/null; then
            echo -e "${red}${bold}Error: Java installation failed.${clear}"
            exit 1
        fi
    fi
}

# Download the server.jar file from Mojang's official servers
server_download() {
    if [ "$java_installed" = true ]; then
        if [ -d "$server_directory" ]; then
            echo -e "${green}${bold}Erasing contents of $server_directory. This may require sudo privileges...${clear}"
            sudo rm -rf $server_directory
            mkdir -p $server_directory
            cd $server_directory
            echo -e "${green}${bold}Downloading server.jar...${clear}"
            wget "$server_link"
            if [ $? -eq 0 ]; then
                echo -e "${green}${bold}Download successful.${clear}"
            else
                echo -e "${red}${bold}Download failed. Check your internet connection and try again.${clear}"
                exit
            fi
        else
            echo -e "${green}${bold}Creating proper directories...${clear}"
            mkdir -p $server_directory
            cd $server_directory
            echo -e "${green}${bold}Downloading server.jar...${clear}"
            wget "$server_link"
            if [ $? -eq 0 ]; then
                echo -e "${green}${bold}Download successful.${clear}"
            else
                echo -e "${red}${bold}Download failed. Check your internet connection and try again.${clear}"
                exit
            fi
        fi
    else
        :
    fi
}

# Set up the server and accept the EULA
server_setup() {
    eula='eula=true'
    cd $server_directory
    echo -e "${green}${bold}Running server.jar...${clear}"
    $server_run
    echo -e "${green}${bold}Accepting EULA...${clear}"
    echo "$eula" > "$server_directory/eula.txt"
    echo -e "${green}${bold}Creating server...${clear}"
    cp ~/MineInstall/start ~/server/start
    cp ~/MineInstall/uninstall ~/server/uninstall
}

check_java
if $java_installed: then
    server_download
    server_setup
