#!/bin/bash

# This simple script downloads and installs a Minecraft server onto your computer/server.

server_version="1.20.2"
server_link=https://piston-data.mojang.com/v1/objects/5b868151bd02b41319f54c8d4061b8cae84e665c/server.jar
server_run="java -Xmx1024M -Xms1024M -jar server.jar nogui"

green='\e[42m'
red='\e[31m'
bold='\e[1m'
clear='\e[0m'

# Check if Java is installed
check_java() {
    java_installed=false

    if command -v java &>/dev/null; then
        echo $green$bold"Checking Java version..."$clear
        java_version=$(java --version 2>&1)
        if [ $? -eq 0 ]; then
            java_installed=true
        else
            echo $red$bold"Error: Java is not installed or an problem occurred while checking the version."$clear
            exit
        fi
    else
        echo $red$bold"Error: Java is not installed."$clear
        exit
    fi
}

# Download the server.jar file from Mojang's official servers
server_download() {
    if [ "$java_installed" = true ]; then
        server_directory=~/server
        if [ -d "$server_directory" ]; then
            echo $green$bold"Creating proper directories..."$clear
            cd ~
            mkdir -p server
            cd server
            echo $green$bold"Downloading server.jar..."$clear
            wget -q "$server_link"
            if [ $? -eq 0 ]; then
                echo $green$bold"Download successful."$clear
            else
                echo $red$bold"Download failed. Check your internet connection and try again."$clear
                exit
            fi
        else
            echo $green$bold"Creating proper directories..."$clear
            mkdir -p "$server_directory"
            cd "$server_directory"
            echo $green$bold"Downloading server.jar..."$clear
            wget -q "$server_link"
            if [ $? -eq 0 ]; then
                echo $green$bold"Download successful."$clear
            else
                echo $red$bold"Download failed. Check your internet connection and try again."$clear
                exit
            fi
        fi
    else
        :
    fi
}


#Set up the server and accept the EULA
server_setup() {
    eula='eula=true'
    cd ~
    cd server
    echo $green$bold"Running server.jar..."$clear
    $server_run
    sleep 10
    echo $green$bold"Accepting EULA..."$clear
    echo "$eula" > "$server_directory/eula.txt"
    echo $green$bold"Creating server..."$clear
    cp ~/Mineinstall/start ~/server/start
    cp ~/Mineinstall/uninstall ~/server/uninstall
}

check_java
server_download
server_setup
