#!/bin/bash

#Run this script to uninstall the Minecraft server and delete any associated files.

#WARNING: THIS WILL DELETE YOUR SERVER, ITS WORLD, AND ALL PLAYER DATA. RUN AT YOUR OWN RISK.

is_true=""
while [ "$is_true" != "true" ] && [ "$is_true" != "false" ]; do
    echo -n "Do you want to continue? Keep in mind that this will delete your server, its world, and all player data. (y/n): "
    read response

    if [ "$response" == "y" ] || [ "$response" == "Y" ]; then
        is_true=true
    elif [ "$response" == "n" ] || [ "$response" == "N" ]; then
        is_true=false
    else
        echo "Invalid input. Please enter 'y' or 'n'."
    fi
done

if [ "$is_true" == "true" ]; then
    rm -rf ~/server
else
    echo Uninstallation aborted.
fi
